name: Update Issue #233

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Update issue #233
      env:
        ISSUE_NUMBER: 233
        TARGET_DATE: "2024-10-3T21:00:00Z" 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Calculate the remaining time until the target date
        NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        TARGET=$TARGET_DATE
        REMAINING_SECONDS=$(($(date -d $TARGET +%s) - $(date -d $NOW +%s)))

        # Convert remaining seconds into days, hours, minutes
        DAYS_LEFT=$((REMAINING_SECONDS / 86400))
        HOURS_LEFT=$(( (REMAINING_SECONDS % 86400) / 3600))
        MINUTES_LEFT=$(( (REMAINING_SECONDS % 3600) / 60))
        SECONDS_LEFT=$((REMAINING_SECONDS % 60))

        # Generate the message
        MESSAGE="⏳ Time remaining until target date: $DAYS_LEFT days, $HOURS_LEFT hours, $MINUTES_LEFT minutes, $SECONDS_LEFT seconds."

        # Use GitHub API to update the issue
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"$MESSAGE\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER
