name: Build and Run Minetest with VoxelForge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Minetest dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          libirrlicht-dev \
          libsqlite3-dev \
          libpng-dev \
          libjpeg-dev \
          libbz2-dev \
          libcurl4-openssl-dev \
          libpugixml-dev \
          libvorbis-dev \
          libogg-dev \
          libtinyxml-dev \
          libgmp-dev \
          liblzma-dev \
          zlib1g-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev

    - name: Download Minetest source
      run: |
        git clone --branch master https://github.com/minetest/minetest.git
        cd minetest
        git submodule update --init --recursive

    - name: Compile Minetest
      run: |
        cd minetest
        rm -rf build
        mkdir -p build
        cd build
        cmake .. -DENABLE_SOUND=0
        make -j$(nproc)

    - name: Upload Build Logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: minetest/build/build_output.log

    - name: Verify Build
      run: |
        cd minetest/build
        echo "Listing files in the build directory:"
        ls -l
        echo "Searching for Minetest executable:"
        find . -type f -name 'minetest' -exec ls -l {} \;

    - name: Download VoxelForge subgame
      run: |
        cd ..
        git clone https://github.com/voxelforge/voxelforge.git

    - name: Run Minetest with VoxelForge
      run: |
        cd minetest/build
        if [ -f minetest ]; then
          ./minetest --gameid voxelforge --world world_test --config /dev/null
        else
          echo "Minetest executable not found. Skipping execution."
          exit 1
        fi
